In [2]:
import numpy as np

In [8]:
v = np.arange(1, 11)
print(v)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
mx = np.zeros((3, 3))
print(mx)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
mxr = np.random.randint(1, 11, size=(5, 5))
print(mxr)

[[ 8 10  8 10  4]
 [ 7  4  1  2  3]
 [ 3 10  7  5  7]
 [ 4  8 10  3  6]
 [ 3  3  1  7  4]]


In [7]:
mxr = np.random.rand(4, 4)
print(mxr)

[[0.05342774 0.04813241 0.3770493  0.68700984]
 [0.56324392 0.6933675  0.92849092 0.0166773 ]
 [0.33731627 0.88456655 0.06356033 0.95002905]
 [0.94422467 0.45939032 0.36122575 0.90656696]]


In [12]:
v1 = np.random.randint(1, 11, size=5)
v2 = np.random.randint(1, 11, size=5)

print(f'V1: {v1}\nV2: {v2}')

print(v1 + v2)
print(v1 - v2)
print(v1 * v2)

V1: [7 1 5 4 6]
V2: [ 9  8  7 10  7]
[16  9 12 14 13]
[-2 -7 -2 -6 -1]
[63  8 35 40 42]


In [15]:
v1 = np.random.randint(1, 11, size=7)
v2 = np.random.randint(1, 11, size=7)
print(f'V1: {v1}\nV2: {v2}')
print("Скалярний добуток:", np.dot(v1, v2))

V1: [7 5 4 6 6 2 4]
V2: [ 8  7 10  4 10  3  2]
Скалярний добуток: 229


In [18]:
mx1 = np.random.randint(1, 11, size=(2, 2))
mx2 = np.random.randint(1, 11, size=(2, 3))

print(f"Результат перемноження двох матриць:\n{np.dot(mx1, mx2)}")

Результат перемноження двох матриць:
[[ 39  81  21]
 [ 39 113  24]]


In [21]:
mx = np.random.randint(1, 11, size=(3, 3))
print(mx)
print(np.linalg.inv(mx))

[[ 8  9  3]
 [ 1  6 10]
 [ 1  3  9]]
[[ 0.125      -0.375       0.375     ]
 [ 0.00520833  0.359375   -0.40104167]
 [-0.015625   -0.078125    0.203125  ]]


In [23]:
mx = np.random.rand(4, 4)
print(mx)
print(mx.T)

[[0.66015467 0.49539098 0.84248805 0.68693939]
 [0.86436062 0.69389171 0.20840295 0.78732381]
 [0.73873257 0.15407282 0.01720302 0.09177894]
 [0.72711328 0.76405445 0.29576892 0.85174034]]
[[0.66015467 0.86436062 0.73873257 0.72711328]
 [0.49539098 0.69389171 0.15407282 0.76405445]
 [0.84248805 0.20840295 0.01720302 0.29576892]
 [0.68693939 0.78732381 0.09177894 0.85174034]]


In [27]:
mx = np.random.randint(1, 11, size=(3, 4))
v = np.random.randint(1, 11, size=(4, ))
print(np.dot(mx, v))

[111 102 122]


In [26]:
mx = np.random.rand(2, 3)
v = np.random.rand(3)
print(np.dot(mx, v))

[1.0427024  0.53202684]


In [29]:
mx1 = np.random.randint(1, 11, size=(2, 2))
mx2 = np.random.randint(1, 11, size=(2, 2))
print(mx1*mx2)

[[18  8]
 [60 12]]


In [31]:
mx1 = np.random.randint(1, 11, size=(2, 2))
mx2 = np.random.randint(1, 11, size=(2, 2))
print(np.dot(mx1, mx2))

[[ 59  40]
 [106  82]]


In [33]:
mx = np.random.randint(1, 101, size=(5, 5))
print(np.sum(mx))

1023


In [35]:
mx1 = np.random.randint(1, 11, size=(4, 4))
mx2 = np.random.randint(1, 11, size=(4, 4))
print(mx2-mx1)

[[ 3  0 -1  1]
 [-6  6  4 -4]
 [ 1  3  3 -2]
 [ 8 -5 -2 -4]]


In [37]:
mx = np.random.rand(3, 3)
row_sums = np.sum(mx, axis=1, keepdims=True)
print(row_sums)


Вектор-стовпчик із сумами рядків матриці:
[[2.54228322]
 [1.74809948]
 [1.7737126 ]]


In [38]:
mx = np.random.randint(1, 11, size=(3, 4))
print(mx**2)

[[ 25   4  64  49]
 [ 25  25  36  64]
 [100   9  25   1]]


In [39]:
v = np.random.randint(1, 51, size=(4, ))
print(np.sqrt(v))

[4.89897949 3.31662479 4.79583152 6.55743852]
